groups:
  - name: vault
    rules:
      - alert: VaultTooManyPendingTokens
        expr: avg(vault_token_create_count - vault_token_store_count) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Vault too many pending tokens (instance {{ $labels.instance }})
          description: "Too many pending tokens {{ $labels.instance }}: {{ $value | printf \"%.2f\"}}%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: VaultTooManyInfinityTokens
        expr: vault_token_count_by_ttl{creation_ttl="+Inf"} > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Vault too many infinity tokens (instance {{ $labels.instance }})
          description: "Too many infinity tokens {{ $labels.instance }}: {{ $value | printf \"%.2f\"}}%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: VaultUninitialized
        expr: avg by(instance) (vault_initialized) != 1
        for: 3m
        labels:
          service: vault
          severity: critical
        annotations:
          summary: "Vault instance `{{$labels.instance}}` is uninitialized"
          description: "The Vault instance at `{{$labels.instance}}` has been uninitialized for the last <%= p('vault_alerts.initialized.evaluation_time') %>"

      - alert: VaultSealed
        expr: vault_core_unsealed == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Vault sealed (instance {{ $labels.instance }})
          description: "Vault instance is sealed on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    
      - alert: VaultStandby
        expr: count(avg by(instance) (vault_standby) == 0) != 1
        for: 5m
        labels:
          service: vault
          severity: critical
        annotations:
          summary: "There are {{ $value }} active Vault instance(s)"
          description: "The Vault instance at `{{$labels.instance}}` has been Standby for the last <%= p('vault_alerts.standby.evaluation_time') %>"

      - alert: VaultLeadershipLoss
        expr: sum(increase(vault_core_leadership_lost_count{job="vault"}[1h])) > 5
        for: 1m
        labels:
          service: vault
          severity: critical
        annotations:
          summary: " High frequency of Vault leadership losses"
          description: "There have been more than 5 Vault leadership losses in the past 1h"

      - alert: VaultLeadershipStepDowns
        expr: sum(increase(vault_core_step_down_count{job="vault"}[1h])) > 5
        for: 1m
        labels:
          service: vault
          severity: critical
        annotations:
          summary: "High frequency of Vault leadership step downs"
          description: "There have been more than 5 Vault leadership step downs in the past 1h"

      - alert: VaultLeadershipSetupFailures
        expr: sum(increase(vault_core_leadership_setup_failed{job="vault"}[1h])) > 5
        for: 1m
        labels:
          service: vault
          severity: critical
        annotations:
          summary: "High frequency of Vault leadership setup failures"
          description: "There have been more than 5 Vault leadership setup failures in the past 1h"          
